services:
  consumer:
    build:
      context: ./service-consumer
      dockerfile: dockerfile
    container_name: service-consumer
    environment:
      - VITE_CONSUMER_URL=http://localhost
      - VITE_REGISTRY_URL=http://localhost:3000
    ports:
      - "80:3000"

  registry:
    build:
      context: ./service-registry
      dockerfile: dockerfile
    stop_signal: SIGINT
    container_name: service-registry
    ports:
      - "3000:3000"

  spotify:
    build:
      context: ./service-providers/spotify-music-manager
      dockerfile: dockerfile
    depends_on:
      - registry
    stop_signal: SIGINT
    container_name: service-provider-spotify
    environment:
      - PROVIDER_URL=http://localhost:3001
      - REGISTRY_URL=http://localhost:3000
    ports:
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  apple:
    build:
      context: ./service-providers/apple-music-manager
      dockerfile: dockerfile
    depends_on:
      - registry
    stop_signal: SIGINT
    container_name: service-provider-apple
    environment:
      - PROVIDER_URL=http://localhost:3002
      - REGISTRY_URL=http://localhost:3000
    ports:
      - "3002:3002"
    extra_hosts:
      - "host.docker.internal:host-gateway"
