# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Install Flask
RUN pip3 install Flask requests flask-cors

# Copy the Python file into the container
COPY main.py /app/main.py

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Run the Flask application
CMD ["python3", "main.py"]
