FROM node:lts-alpine

WORKDIR /app

RUN npm install -g serve

COPY package*.json ./
RUN npm install

COPY vercel.json ./
COPY vite.config.js ./
COPY index.html ./
COPY public/ ./public
COPY src/ ./src

CMD npm run build && serve --config ../vercel.json dist
